### ISSUE TITLE
CPAN: not found

### ISSUE THREAD

**Issue by szepeviktor** [dkogan/feedgnuplot#22]
Is it OK?

```
# cpan feedgnuplot
Going to read '/root/.cpan/Metadata'
  Database was generated on Thu, 26 Feb 2015 02:17:01 GMT
Warning: Cannot install feedgnuplot, don't know what it is.
Try the command

    i /feedgnuplot/

to find objects with matching identifiers.
```

**Comment by dkogan** [comment]
This is a known issue. Apparently CPAN doesn't like packages that don't
have .pm files (which this one does, since it's an executable). The
suggestion was to create a dummy .pm file, which I didn't want to do.
Maybe I still should. Let me think about it. Discussion:

 https://github.com/dkogan/feedgnuplot/pull/16

**Comment by szepeviktor** [comment]
Thank you for your answer.
